### ISSUE TITLE
Именованный экспорт в версии 1.3.0

### ISSUE THREAD

**Issue by AlexChebanenko** [xobotyi/cnbuilder#12]
**Do you want to request a _feature_ or report a _bug_?**
Баг

**What is the current behavior?**
Присутствует именованный экспорт в версии 1.3.0.

В версии 1.3.0 произошло изменение, обратно несовместимое с версией 1.1.7.

Сборки падают.

```
./node_modules/react-scrollbars-custom/dist/rsc.esm.js
Attempted import error: 'cnbuilder' does not contain a default export (imported as 'cnb').
```

**What is the expected behavior?**
Изменения с увеличением минорной версии обратно совместимы

**Comment by xobotyi** [comment]
1.3 is marked as deprecared.
Ive made a typo and semantic release did not counted release as major.
Use 1.2 instead.

**Comment by xobotyi** [comment]
ill release 1.3.1 fix in coule of minutes.

**Comment by xobotyi** [comment]
Recheck now with 1.3.1 please.
Sorry for inconvinience.

**Comment by xobotyi** [comment]
fixed with v1.3.2 release
